name: weather_app
description: "A weather app which is web-compatible"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1
  dev: ^1.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  dio: ^5.8.0+1
  riverpod_lint: ^2.6.3
  flutter_map_location_marker: ^9.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
